# Generated by Django 4.0.2 on 2024-04-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sellin_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('descirption', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.CharField(choices=[('CR', 'Curd'), ('ML', 'Milk'), ('LS', 'Lassi'), ('MS', 'Milkshake'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('CZ', 'Cheese'), ('IC', 'Ice-Creams')], max_length=2)),
                ('Product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
