# Generated by Django 4.0.2 on 2024-04-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('ML', 'Milk'), ('LS', 'Lassi'), ('MS', 'Milkshake'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('CZ', 'Cheese'), ('IC', 'Ice-Creams')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='prodapp',
            field=models.TextField(default=''),
        ),
    ]
