# Generated by Django 4.0.2 on 2024-04-23 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_category_alter_product_prodapp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_image',
            new_name='product_image',
        ),
    ]
