# Generated by Django 4.0.2 on 2024-04-23 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_product_image_product_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sellin_price',
            new_name='selling_price',
        ),
    ]
