# Generated by Django 4.0.2 on 2024-04-26 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_payment_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='rozorpay_order_id',
            new_name='razorpay_order_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='rozorpay_payment_id',
            new_name='razorpay_payment_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='rozorpay_payment_status',
            new_name='razorpay_payment_status',
        ),
    ]
