# Generated by Django 4.0.2 on 2024-04-26 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='Product',
            new_name='product',
        ),
    ]
